### ISSUE TITLE
TeX and LaTeX logos

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-project.github.io#12]
Out of curiosity, I went looking to see if anyone had reproduced the TeX and LaTeX logos as anything other than images online and found this: http://edward.oconnor.cx/2007/08/tex-poshlet

Looking at it, this would be fairly easy to implement in our pages if we wanted to do it, but I thought I'd ask to see if others liked the idea before doing any work to make it happen.

**Comment by eroux** [comment]
sounds good to me!

**Comment by rpspringuel** [comment]
Implemented with commit e67fd1e on my fork.  This is part of my work on updating the website for 4.0 and thus won't show immediately.
