### ISSUE TITLE
update gabc sign description 

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio-project.github.io#14]
The [gabc sign description](http://gregorio-project.github.io/gabc/details.html#signs) is quite outdated and doesn't describe all 4.0 features. See [UPGRADE.md](https://github.com/gregorio-project/gregorio/blob/release-4.0/UPGRADE.md#horizontal-episema-improvements) for the description of the new horizontal episemus features. Note that the [new vertical episemus features](https://github.com/gregorio-project/gregorio/issues/385) don't seem to be described in UPGRADE.md

**Comment by rpspringuel** [comment]
Do you have an example of a situation where `_2` is different from `_`?  I'm having trouble figuring out a case where this one has an effect.

**Comment by rpspringuel** [comment]
Found one: `H_2g_`

**Comment by rpspringuel** [comment]
Questions:
1. Are there circumstances where an unmodified vertical episema (i.e. `'`) is automatically placed above the note?
2. Likewise for the horizontal episema?

**Comment by henryso** [comment]
Yes, there are cases where the automatically placed episema is above.  See gregoriotex-position.c for the logic.

**Comment by rpspringuel** [comment]
See 2c5b623 for new changes.

**Comment by rpspringuel** [comment]
Done in #13
