### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-project.github.io#19]
My confrere feels that the Kyrie is too complicated a score for the tutorial and feels we'd be better served with a score which doesn't have quite so many complicated neumes.  As he went through the tutorial, he found himself simply copying and pasting the notes from the webpage, rather than taking the time to enter them himself.  He suggests using a simpler score which uses a lot of single note syllables (he's working his way through a Magnificat right now) to avoid that temptation.  The Kyrie would then become an "advanced" tutorial.

**Comment by rpspringuel** [comment]
He's also suggested using the `\gabcsnippet` command for the simpler tutorial as then there's only one file for the real novice to get used to.  The idea of a separate (and reusable) gabc file would then be part of the advanced tutorial.

**Comment by henryso** [comment]
This is not an argument for or against what you have said, but rather just a note.  The original purpose of the gabc snippet feature is to allow quick inclusions of small bits of chant, and not to include long-form scores.  It is also a little less robust than separate files (for example, mismatched braces will break it).  We just need to be sure we're OK encouraging the use of gabc snippet to include long scores (which people _will do_, especially if it's in the tutorial).

See gregorio-project/gregorio#367 for more background.

**Comment by rpspringuel** [comment]
I understand what `\gabcsnippet` is for, I'm just noting that a complete novice after working through the tutorial found the "advanced" `\gabcsnippet` command much easier to work with as he was learning (particularly in practicing his note entry).

Do you think people would pay attention if we placed something at the end of a "simple" tutorial which used `\gabcsnippet` which noted said command was meant for short bits of chant (call it 3 lines of music or less)?

Further, as is `\gabcsnippet` will work just fine with long blocks of gabc, even if it isn't meant for that.  Would it make sense to impose some sort of limit on the size of what it can work with (thereby forcing users to make use of separate score files for longer scores)?

**Comment by henryso** [comment]
This is really a question of "spin".  I don't think we should enforce any particular usage of `\gabcsnippet`.  I guess a warning about the proper usage of `\gabcsnippet` is enough.  Perhaps one at the beginning and one at the end of the "simple" tutorial?

**Comment by eroux** [comment]
I think it's a good idea to use `\gabcsnippet` to simplify the tutorial, with warnings
