### ISSUE TITLE
Build and install to non-system-wide directory

### ISSUE THREAD

**Issue by igneus** [gregorio-project/gregorio-project.github.io#22]
It would be great if some gregorio-installation-guru expanded http://gregorio-project.github.io/installation-linux.html by instructions on how to build and install gregorio to custom "/usr/local" directory (e.g. to "~/my_usr") and the user's texmf directory.

I tried to read through the build scripts, but I failed to find the answer.

**Comment by henryso** [comment]
```
./build.sh --prefix=/path/to/custom/root
sudo ./install.sh dir:/path/to/custom/texmf
```

Generally, `build.sh` takes the arguments for `configure` and `install.sh` takes the arguments for `install-gtex.sh`.
