### ISSUE TITLE
documenting oriscus orientation in basic gabc instructions

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio-project.github.io#44]
It would be worth mentionning `o0` and `o1` in http://gregorio-project.github.io/gabc/index.html#onenote

**Comment by martindonat** [comment]
I had a look on it, but isn't `o0` the same `o`?

Furthermore I made same more minor changes:
* Fixed some broken links in gregoriotex/examples
* Made a more visible "Next Page"-Link in the tutorial (I found pages 2 and 3 weeks after page 1, and the snippet tutorial I just found today by looking at the html files in the repo)
* Fixed some wrong/old GregorioTeX commands
* I would recommend to upload the full documentation somewhere in the tutorials. At the moment you can just have a look at them after installing Gregorio.

Besides that I would work on a major overhaul of the structure of the website. I will make some suggestions in new issue.

If you could give me hint on this issue (`o0` vs `o`) I will make a pull request soon.

**Comment by henryso** [comment]
`o0` is an oriscus that points down. `o` is an oriscus whose direction depends on the first non-unison note that comes after it.

**Comment by martindonat** [comment]
Finally I was able to finish it. Sorry, there were some obstacles and in the end I had some beginner difficulties with git...

I have some ideas for a reorganisation of the website and will present them in a new issue soon.
