### ISSUE TITLE
Misplaced horizontal episema

### ISSUE THREAD

**Issue by ebydj1** [gregorio-project/gregorio-project.github.io#53]
When I try to write this:

`præ(j_h)`

I see this:

![screenshot from 2016-11-18 23-13-24](https://cloud.githubusercontent.com/assets/4675370/20452948/a3d6d30a-ade4-11e6-9e4c-e66a59693276.png)

In a previous version of Gregorio the horizontal episema was on the first note. I can't figure out how to place it on the first note now. (The example is from the gradual of the Immaculate Conception, for the record.)

**Comment by henryso** [comment]
This issue is misplaced.  Please reopen it in gregorio-project/gregorio.

**Comment by martindonat** [comment]
So, can we close this issue?

**Comment by ebydj1** [comment]
I'm fine with that... Sorry for dropping the issue a while back.
