### ISSUE TITLE
Mailing lists are down

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-project.github.io#61]
It appears that the mailing lists are down and that gna.org is unreachable.  Based on the archives, they've been this way since 23 May.  Does anyone have any way of reaching the gna.org people to find out what's going on and when things will be up again?

Or do we want to use this as an impetus to get off of gna.org entirely since we no longer use their system for development?

**Comment by eroux** [comment]
Hmmm according to https://github.com/Boussau/PHYLDOG/issues/4 gna is shutting down... I admit I'm a bit surprised, I cannot remember receiving a notice about that... I think some google groups should be set up for the mailing list, and a mail should be sent to the people who sent a mail to the user mailing list with a link to the new group. That's quite unfortunate...

**Comment by henryso** [comment]
@eroux Are you able to get a list of subscribers of the old lists?

**Comment by eroux** [comment]
No, I don't know how to get that...

**Comment by rpspringuel** [comment]
I've been looking at our various mailing list archives, and none of them appear to have email addresses that could be scraped off (which is good, from a spam prevention point of view).  I think the best we could do would be to look into our personal email histories and compile a list of all the addresses which sent messages to the list in the past year or so that we still have floating around.

@eroux, do you want to take charge of setting up the Google group?

**Comment by eroux** [comment]
Not really... I'm wondering if we could use the Gmane thing? or is it read only?

**Comment by henryso** [comment]
I think Gmane is a mailing list aggregator, not a mailing list itself.

**Comment by codefisher** [comment]
Email given near the top of this page: https://github.com/gregorio-project is still the old one.

**Comment by rpspringuel** [comment]
Changed.  Thanks for noticing that.

**Comment by fradec** [comment]
It seems that it's not possible to access to the group online if you not have a google account (which is my case for example). It is thus difficult to manage the notifications or the email address for reception or to consult the archives of the new group.
Do you know how to do this easily?

**Comment by rpspringuel** [comment]
The settings should allow you to access the group archives without a Google account.  Try https://groups.google.com/forum/#!forum/gregorio-users

As I don't have a non-Google managed email account, I can't check how the list management options work for such an address.

**Comment by henryso** [comment]
I have a Google account that's registered under a non-gmail address.  I log into that account, navigate to Google groups, and can change my message frequency settings there.

**Comment by fradec** [comment]
Henry's solution works fine. All is ok for me now. Thanks!
