### ISSUE TITLE
Spaces and line

### ISSUE THREAD

**Issue by graduelfm** [gregorio-project/gregorio-project.github.io#64]
Hello all!
I'm a new user of Gregorio and I need some help.
Could you give me some answer about my questions :
- how could I insert a space or a line between "Biblical-reference" and the first staff ? Sometimes, the notes are too high and are on the same spot than the biblical-reference.
- how is it possible to insert space/line between annotations (name of the piece and mode indication) above the initial?
- how could I change the line spacing between text and the next staff?
Many thanks for yours answers.
Have a nice sunny day!
All the best.
Florence

PS : sorry, if it's not the place to ask this kind of questions. Othewise, where can I find some help? Or find some french documentation about Gregorio? Thank you.

**Comment by rpspringuel** [comment]
The appropriate place to ask these questions is on the mailing list, which you seem to have found already.

Unfortunately we don't have any French documentation for Gregorio at the moment.  We simply don't have the developer resources to maintain a translation of the documentation.

**Comment by graduelfm** [comment]
Thank you for your answer.
