### ISSUE TITLE
Macro for TeXShop

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-project.github.io#70]
I've developed a macro for TeXShop which will syllabify the selected text using the syllabifier in hyphen-la.  Unfortunately it's not a simple thing to upload the macro to the contrib folder of the main repository because of the way it works: the macro is written in AppleScript and thus can't make use PATH configurations to find user commands and thus must rely on explicit full paths.  Would it be alright if I wrote up a "Tip-n-Trick" which explained how a user could create the same script on their own setup?

**Comment by henryso** [comment]
I think a tip-and-trick for this is better unless those issues can be resolved.

**Comment by rpspringuel** [comment]
See #71
