### ISSUE TITLE
Broken link to summary-gabc.pdf

### ISSUE THREAD

**Issue by avbop** [gregorio-project/gregorio-project.github.io#8]
According to the [W3C link checker](https://validator.w3.org/checklink?uri=https%3A%2F%2Fgregorio-project.github.io%2F&summary=on&hide_type=all&recursive=on&depth=5&check=Check), `gabc/index.html` links to `gabc/summary-gabc.pdf`, which doesn't exist. I also couldn't find that file anywhere else.

**Comment by veromary** [comment]
This might be it 
http://gregobase.selapa.net/wp-content/uploads/2014/08/summary-gabc.pdf

**Comment by henryso** [comment]
Actually, it's most likely http://home.gna.org/gregorio/gabc/summary-gabc.pdf, though this old document is pretty out-of-date.  I'll admit Gregobase's summary is nicer, but that's their work.  In any case, I'll pull the old document from gna.org into here.  Does anyone know where the TeX/gabc source for this document is?
