### ISSUE TITLE
Separate translation and above lines text documentation

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-project.github.io#91]
Right now the translation and above lines text documentation share a section on the website (http://gregorio-project.github.io/gabc/details.html#translation).  This can make it harder to find one or the other (usually the above lines text, because it is talked about second).

Additionally, the description of above lines text describes two ways of entering it, but only one is demonstrated in the image.

**Comment by graduelfm** [comment]
Good morning,
Is there a possibility to write the above line text in color?
I tried to use :
<c><alt>abovelinetext</alt></c> 
and 
<alt><c>abovelinetext</c></alt>
but the both doesn't work. There is no color with these commands.
Could I use an another command to put in the gabc file to have the color on the above line text?
Thank you for your answer.
All the best,
Florence

**Comment by graduelfm** [comment]
Good morning,
Is there a possibility to write the above line text in color?
I tried to use :
"<c><alt>abovelinetext</alt></c>"
and
"<alt><c>abovelinetext</c></alt>"
but the both doesn't work. There is no color with these commands.
Could I use an another command to put in the gabc file to have the color on the above line text?
Thank you for your answer.
All the best,
Florence

**Comment by graduelfm** [comment]
Good morning,
Is there a possibility to write the above line text in color?
I tried to use :
"<c>""<alt>"abovelinetext"</alt>""</c>"
and
"<alt>""<c>"abovelinetext"</c>""</alt>"
but the both doesn't work. There is no color with these commands.
Could I use an another command to put in the gabc file to have the color on the above line text?
Thank you for your answer.
All the best,
Florence

**Comment by graduelfm** [comment]
Good morning,
Is there a possibility to write the above line text in color?
I tried to use the command "c" and "/c" before and after the command "alt" and "/alt" but the both doesn't work. There is no color with these commands.
Could I use an another command to put in the gabc file to have the color on the above line text?
Thank you for your answer.
All the best,
Florence

**Comment by rpspringuel** [comment]
Please don't hijack issues for tech support.  Support requests should be emailed to the user group: gregorio-users@googlegroups.com

**Comment by graduelfm** [comment]
Dear rpspringuel. Thank you for your answer. I will do it. Have a nice day

**Comment by graduelfm** [comment]
Thank you for your answer. I tried to send an email to this adress, but it doesn't work. Could you help me?

Many thanks

 

Envoyé: lundi 26 octobre 2020 à 14:47
De: "Br. Samuel Springuel" <notifications@github.com>
À: "gregorio-project/gregorio-project.github.io" <gregorio-project.github.io@noreply.github.com>
Cc: "graduelfm" <graduel.fm@gmx.fr>, "Comment" <comment@noreply.github.com>
Objet: Re: [gregorio-project/gregorio-project.github.io] Separate translation and above lines text documentation (#91)


 

Please don't hijack issues for tech support. Support requests should be emailed to the user group: gregorio-users@googlegroups.com

**Comment by rpspringuel** [comment]
You need to sign-up for the group before you can post: https://groups.google.com/forum/#!forum/gregorio-users

**Comment by graduelfm** [comment]
Thank you for your help.

God bless you

 
 

Envoyé: mardi 27 octobre 2020 à 14:41
De: "Br. Samuel Springuel" <notifications@github.com>
À: "gregorio-project/gregorio-project.github.io" <gregorio-project.github.io@noreply.github.com>
Cc: "graduelfm" <graduel.fm@gmx.fr>, "Comment" <comment@noreply.github.com>
Objet: Re: [gregorio-project/gregorio-project.github.io] Separate translation and above lines text documentation (#91)


 

You need to sign-up for the group before you can post: https://groups.google.com/forum/#!forum/gregorio-users
